ad css_sso
probationer070/ProjShop pull request #15
Opened 2024-07-17 06:57 UTC by ssoeun1

login & member search & register & user product list & detail  fix css

2024-07-17 07:07 UTC, probationer070 commented on src/main/java/com/ecom6/VO/notice/NoticeVO.java
> -	private String text;
원본 유지

2024-07-17 07:20 UTC, probationer070 requested changes
요청사항 확인

2024-07-17 07:20 UTC, probationer070 commented on src/main/java/com/ecom6/service/notice/NoticeService.java
원본 유지

2024-07-17 07:20 UTC, probationer070 commented on src/main/java/com/ecom6/service/notice/NoticeService.java
원본 유지

2024-07-17 07:20 UTC, probationer070 commented on src/main/java/com/ecom6/web/notice/NoticeController.java
원본 유지

2024-07-17 07:20 UTC, probationer070 commented on src/main/resources/static/images/blue_dot.gif
삭제 필요

2024-07-17 07:20 UTC, probationer070 commented on src/main/webapp/WEB-INF/views/layouts/header.jsp
>  <link rel="stylesheet" href="../css/layouts.css" />
원본 유지

2024-07-17 07:20 UTC, probationer070 commented on src/main/webapp/WEB-INF/views/popup/pwCheck_popup.jsp
>  					<button class="btn btn-outline-primary pwck" value="확인">확인</button>
원본 유지

2024-07-17 08:01 UTC, HanDooSeong requested changes

2024-07-17 08:01 UTC, HanDooSeong commented on src/main/webapp/WEB-INF/views/layouts/header.jsp
> -
원본유지

2024-07-17 08:01 UTC, HanDooSeong commented on src/main/resources/static/css/layouts.css
> -    --font-color-base: #000;
원본유지

2024-07-17 08:26 UTC, ssoeun1 commented on src/main/resources/static/images/blue_dot.gif
사용중, 삭제 불가

2024-07-17 09:01 UTC, probationer070 commented on src/main/java/com/ecom6/dao/mapper/ProductMapper.xml
> -
원본 유지

2024-07-17 09:02 UTC, HanDooSeong commented on src/main/webapp/WEB-INF/views/layouts/swiper.jsp
> -      <div id="contents" style="margin-top: 20px;">
원본유지

2024-07-17 09:08 UTC, probationer070 requested changes

2024-07-17 09:08 UTC, probationer070 commented on src/main/java/com/ecom6/dao/notice/NoticeDao.java
> -	int getSearch(String string);
원본 유지

2024-07-17 09:08 UTC, probationer070 commented on src/main/java/com/ecom6/dao/product/ProductDao.java
> -
원본 유지

2024-07-17 09:08 UTC, probationer070 commented on src/main/java/com/ecom6/service/cart/CartServiceImpl.java
> -		 if (cnt != 0) {
원본 유지

2024-07-17 09:08 UTC, probationer070 commented on src/main/java/com/ecom6/service/product/ProductService.java
원본 유지

2024-07-17 09:08 UTC, probationer070 commented on src/main/java/com/ecom6/service/product/ProductServiceimpl.java
원본 유지

2024-07-17 09:08 UTC, probationer070 commented on src/main/java/com/ecom6/web/api/RestApiController.java
원본 유지

2024-07-17 09:08 UTC, probationer070 commented on src/main/java/com/ecom6/web/cart/CartController.java
> -			model.addAttribute("SubTot", reSet.get("subTotal"));
원본 유지

2024-07-17 09:08 UTC, probationer070 commented on src/main/java/com/ecom6/web/common/MainController.java
> -
원본 유지

2024-07-17 09:08 UTC, probationer070 commented on src/main/java/com/ecom6/web/mem/MemberController.java
원본 유지

2024-07-17 09:08 UTC, probationer070 commented on src/main/java/com/ecom6/web/order/OrderController.java
> -import java.time.format.DateTimeFormatter;
원본 유지

2024-07-17 09:08 UTC, probationer070 commented on src/main/resources/static/css/footer.css
> -html {
원본 유지

2024-07-17 09:08 UTC, probationer070 commented on src/main/resources/static/images/logo-no-background.png
제거 필요

2024-07-17 09:08 UTC, probationer070 commented on src/main/resources/static/js/cart.js
> -	getTotal();
원본 유지

2024-07-17 09:08 UTC, probationer070 commented on src/main/webapp/WEB-INF/views/Main.jsp
>  <head>
원본 유지

2024-07-17 09:08 UTC, probationer070 commented on src/main/resources/static/js/layout.js
> -
원본 유지

2024-07-17 09:08 UTC, probationer070 commented on src/main/webapp/WEB-INF/views/custom/OrderDetail.jsp
> -</script>
원본 유지

2024-07-17 09:08 UTC, probationer070 commented on src/main/webapp/WEB-INF/views/layouts/footer.jsp
> -      </div>
원본 유지

2024-07-17 09:08 UTC, probationer070 commented on src/main/webapp/WEB-INF/views/notice/NoticeList.jsp
> -<script src="../js/pageNation.js" defer="defer"></script>
원본 유지

2024-07-18 01:04 UTC, ssoeun1 reviewed
fix done

2024-07-18 01:05 UTC, probationer070 approved these changes

2024-07-18 01:06 UTC, HanDooSeong approved these changes

2024-07-18 02:22 UTC, probationer070 approved these changes
fix done

2024-07-18 02:23 UTC, merged