add css jiho
probationer070/ProjShop pull request #16
Opened 2024-07-18 02:37 UTC by bburang2

cartList, orderList, orderDetail

2024-07-18 02:43 UTC, probationer070 commented on build.gradle
> -	// PGSYS Libs
원본 유지

2024-07-18 02:55 UTC, probationer070 requested changes

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/VO/notice/NoticeVO.java
> -	private String text;
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/VO/product/ProductVO.java
> -	private String text;
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/dao/cart/CartDao.java
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/dao/mapper/CartMapper.xml
> -	<select id="getCartTotalPrcie" parameterType="String">
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/dao/mapper/NoticeMapper.xml
> -</select>
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/dao/mapper/NoticeMapper.xml
> -	   </if>
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/dao/mapper/ProductMapper.xml
> -	      ]]>
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/dao/notice/NoticeDao.java
> -
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/dao/product/ProductDao.java
> -
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/service/PaymentSys/PgApiService.java
> -
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/service/cart/CartServiceImpl.java
>  		 int cnt = cartDao.getCartItemCnt(mem_id);
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/service/notice/NoticeService.java
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/service/notice/NoticeServiceImpl.java
>  		nvo.setEnd(end);
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/service/product/ProductService.java
> -import java.util.HashMap;
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/service/product/ProductServiceimpl.java
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/web/api/RestApiController.java
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/web/cart/CartController.java
> -			model.addAttribute("SubTot", reSet.get("subTotal"));
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/web/common/MainController.java
> -import java.util.HashMap;
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/web/notice/NoticeController.java
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/web/order/OrderController.java
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/java/com/ecom6/wrapper/search/SearchWrapper.java
> -
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/resources/static/css/ProductList.css
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/resources/static/css/footer.css
> -:root {
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/resources/static/css/layouts.css
>  #join h3{
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/resources/static/images/logo-header-background.png
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/resources/static/images/logo-no-background.png
제거

2024-07-18 02:55 UTC, probationer070 commented on src/main/resources/static/images/mainback.png
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/resources/static/js/layout.js
> +    });
원본에 내용 추가 할 것

2024-07-18 02:55 UTC, probationer070 commented on src/main/webapp/WEB-INF/views/Main.jsp
>  <head>
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/webapp/WEB-INF/views/custom/OrderDetail.jsp
> -		<input type="hidden" name="site_name" value="payup" />
해당 내용 추가 필요

2024-07-18 02:55 UTC, probationer070 commented on src/main/webapp/WEB-INF/views/custom/productDetail.jsp
> -	<div data-ez="contents-1vd3ex7-1" class="xans-element- xans-product xans-product-detail section">
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/webapp/WEB-INF/views/layouts/footer.jsp
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/webapp/WEB-INF/views/layouts/header.jsp
> -<body class="theme03" data-ez-theme="theme03" monica-locale="ko" monica-version="5.8.0" monica-id=
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/webapp/WEB-INF/views/layouts/index.jsp
>      pageEncoding="UTF-8"%>
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/webapp/WEB-INF/views/layouts/swiper.jsp
>  	<!-- Swiper -->
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/webapp/WEB-INF/views/notice/NoticeList.jsp
> -<script src="../js/pageNation.js" defer="defer"></script>
원본 유지

2024-07-18 02:55 UTC, probationer070 commented on src/main/webapp/WEB-INF/views/popup/pwCheck_popup.jsp
>  					<button class="btn btn-outline-primary pwck" value="확인">확인</button>
원본 유지

2024-07-18 02:55 UTC, HanDooSeong commented on src/main/webapp/WEB-INF/views/layouts/header.jsp
> -
지호씨 파일에서 11번 라인까지는 그대로 
쓰시되 부트스트랩 link만 삭제해주시고, 
나머지는 원본 유지해주세요.

2024-07-18 02:55 UTC, HanDooSeong commented on src/main/webapp/WEB-INF/views/layouts/footer.jsp
>      pageEncoding="UTF-8"%>
원본유지

2024-07-19 01:55 UTC, probationer070 approved these changes

2024-07-19 01:55 UTC, merged