07.24 17:53
probationer070/ProjShop pull request #30
Opened 2024-07-24 08:53 UTC by HanDooSeong

2024-07-24 09:04 UTC, probationer070 requested changes

2024-07-24 09:04 UTC, probationer070 commented on src/main/resources/static/js/product.js
> +	$('.psubmit2').on('click', function() {
해당 부분 삭제

2024-07-25 00:30 UTC, probationer070 approved these changes

2024-07-25 00:30 UTC, probationer070 approved these changes

2024-07-25 00:31 UTC, probationer070 approved these changes, later dismissed

2024-07-25 00:31 UTC, probationer070 approved these changes

2024-07-25 00:32 UTC, probationer070 approved these changes

2024-07-25 00:33 UTC, bburang2 approved these changes

2024-07-25 00:33 UTC, merged