doo_fix_admin_error
probationer070/ProjShop pull request #6
Opened 2024-07-10 07:18 UTC by HanDooSeong

-ADMIN
Home 화면에서 logout 버튼 안 눌림.
OrderList의 OrderDetail, 사진 출력 안 됨.
OrderFIX에서 주문정보 출력 오류 및 수정 불가
AdminInfo에서 수정하고 취소눌렀을 때 회원정보수정이 아닌 멤버목록으로 나옴.
Admin NoticeDetail 수정, 삭제 기능 작동 안 됨.
productDetail 수정후 productList로 가짐. productDetail로 이동이 필요

2024-07-10 07:27 UTC, probationer070 requested changes, later dismissed
해당 수정사항 확인필요

2024-07-10 07:27 UTC, probationer070 commented on src/main/resources/static/css/order.css
필요 없는 파일

2024-07-10 07:27 UTC, probationer070 commented on src/main/resources/static/js/common.js
업로드 기준으로 유지

2024-07-11 01:18 UTC, ssoeun1 commented on src/main/resources/static/images/659e4d39d06af6.07046163.jpg
이미지 파일 삭제 요청 드려요

2024-07-11 01:18 UTC, ssoeun1 commented on src/main/resources/static/css/order.css
해당 파일 삭제 요청 드려요

2024-07-11 01:18 UTC, ssoeun1 commented on src/main/resources/static/images/다운로드 black.jfif
이미지 파일 삭제 요청 드려요

2024-07-11 01:18 UTC, ssoeun1 commented on src/main/resources/static/images/다운로드 green.jfif
이미지 파일 삭제 요청 드려요

2024-07-11 01:18 UTC, ssoeun1 commented on src/main/resources/static/images/942299676336736-f5037127-e5d2-4b15-b52b-6fe6a63bcba5.jpg
이미지 파일 삭제 요청 드려요

2024-07-11 01:18 UTC, ssoeun1 commented on src/main/resources/static/images/다운로드 siba.jfif
이미지 파일 삭제 요청 드려요

2024-07-11 01:18 UTC, ssoeun1 commented on src/main/resources/static/images/다운로드 tulip.jfif
이미지 파일 삭제 요청 드려요

2024-07-11 01:18 UTC, ssoeun1 commented on src/main/resources/static/images/다운로드 zflip.jfif
이미지 파일 삭제 요청 드려요

2024-07-11 01:18 UTC, ssoeun1 commented on src/main/resources/static/images/다운로드.jfif
이미지 파일 삭제 요청 드려요

2024-07-11 01:20 UTC, bburang2 submitted a review, later dismissed

2024-07-11 01:20 UTC, bburang2 commented on src/main/java/com/ecom6/VO/notice/NoticeVO.java
m_role 삭제하지 마세요

2024-07-11 01:20 UTC, bburang2 commented on src/main/java/com/ecom6/web/notice/NoticeController.java
세션키 그대로 유지해주세요

2024-07-11 01:20 UTC, bburang2 commented on src/main/resources/static/css/order.css
삭제요망

2024-07-11 01:20 UTC, bburang2 commented on src/main/resources/static/js/common.js
추가해주세요

2024-07-11 01:20 UTC, bburang2 commented on src/main/resources/static/js/member.js
pwCheck2로 변경해주세요

2024-07-11 01:20 UTC, bburang2 commented on src/main/resources/static/js/product.js
FIX로 바꿔주세여

2024-07-11 01:20 UTC, bburang2 commented on src/main/webapp/WEB-INF/views/admin/UpdateForm.jsp
cancel2로 변경해주세요

2024-07-11 01:20 UTC, bburang2 commented on src/main/webapp/WEB-INF/views/custom/CartList.jsp
Proc으로 바꿔주세요

2024-07-11 01:20 UTC, bburang2 commented on src/main/webapp/WEB-INF/views/member/SearchPage.jsp
pwCheck2로 바꿔주세요

2024-07-11 01:41 UTC, probationer070 requested changes
요청사항 적용 바람

2024-07-11 01:41 UTC, probationer070 commented on src/main/webapp/WEB-INF/views/layouts/header.jsp
원본 상태 유지

2024-07-11 01:48 UTC, HanDooSeong reviewed
수정완료

2024-07-11 01:55 UTC, HanDooSeong reviewed
재수정

2024-07-11 01:59 UTC, probationer070 requested changes
재확인 요망

2024-07-11 01:59 UTC, probationer070 commented on src/main/java/com/ecom6/web/notice/NoticeController.java
> +		session.setAttribute("ssKey", ssKey);
코드 위치 if문 안으로 변경 요청

2024-07-11 01:59 UTC, probationer070 commented on src/main/webapp/WEB-INF/views/layouts/header.jsp
업로드 기준 유지

2024-07-11 01:59 UTC, probationer070 commented on src/main/resources/static/js/common.js
업로드 기준 유지

2024-07-11 02:13 UTC, probationer070 approved these changes

2024-07-11 02:15 UTC, merged